classdef Acquisition < handle
    % Acquisition class
    
    properties % GUI
        
        amg % acquisition main GUI

    end
    
    properties
        
        running = 0;
        
        pixelfly;
        
    end
    
    properties
        
        net
        
    end
    
    methods
        
        function obj = Acquisition()
            
            obj = obj@handle;
            
            % create Network class
            
            obj.net = Network.Network(obj);
            
        end
        
        function acquisition_main_gui(obj)
            
            % initialize Vision GUI
            
            obj.amg.h = figure(...
                'Name'                ,'Acquisition Main' ...
                ,'NumberTitle'        ,'off' ...
                ,'Position'           ,[8 48 1904 950] ... %,'MenuBar'     ,'none'...
                );
            
            %%% Block sequence panel %%%
            
            c_ofs = 0.0025;
            r_ofs = 0.86;
            c_wth = 0.495;
            r_wth = 0.13;
            
            obj.amg.hsp1 = uipanel(...
                'Parent'              ,obj.amg.h ...
                ,'Title'              ,'Pixelfly Control' ...
                ,'TitlePosition'      ,'lefttop' ...
                ,'BackgroundColor'    ,Acquisition.Default_parameters.Panel_BackgroundColor ...
                ,'ForegroundColor'    ,Acquisition.Default_parameters.Panel_ForegroundColor ...
                ,'HighlightColor'     ,Acquisition.Default_parameters.Panel_HighlightColor ...
                ,'ShadowColor'        ,Acquisition.Default_parameters.Panel_ShadowColor ...
                ,'FontName'           ,Acquisition.Default_parameters.Panel_FontName ...
                ,'FontSize'           ,Acquisition.Default_parameters.Panel_FontSize ...
                ,'FontUnits'          ,Acquisition.Default_parameters.Panel_FontUnits ...
                ,'FontWeight'         ,Acquisition.Default_parameters.Panel_FontWeight ...
                ,'SelectionHighlight' ,Acquisition.Default_parameters.Panel_SelectionHighlight ...
                ,'Units'              ,Acquisition.Default_parameters.Panel_Units ...
                ,'Position'           ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % pushbutton 1_1 geometry
            
            c_ofs = 2*0.01;
            r_ofs = 0.075;
            c_wth = 2*0.05;
            r_wth = 0.85;
            
            obj.amg.but1_1 = uicontrol(...
                'Parent'                ,obj.amg.hsp1 ...
                ,'Style'                ,'pushbutton' ...
                ,'String'               ,'init. Cam.' ...
                ,'FontName'             ,Acquisition.Default_parameters.Pushbutton_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Pushbutton_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Pushbutton_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Pushbutton_FontWeight ...
                ,'Units'                ,Acquisition.Default_parameters.Pushbutton_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@obj.init_cam ...
                );
            
            % pushbutton 1_2 geometry
            
            c_ofs = 2*0.01+2*(0.05+0.01);
            r_ofs = 0.075;
            c_wth = 2*0.05;
            r_wth = 0.85;
            
            obj.amg.but1_2 = uicontrol(...
                'Parent'                ,obj.amg.hsp1 ...
                ,'Style'                ,'pushbutton' ...
                ,'String'               ,'start Acquis.' ...
                ,'FontName'             ,Acquisition.Default_parameters.Pushbutton_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Pushbutton_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Pushbutton_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Pushbutton_FontWeight ...
                ,'Units'                ,Acquisition.Default_parameters.Pushbutton_Units ...
                ,'BackgroundColor'      ,[0.0 1.0 0.0] ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@obj.start_acquisition ...
                ,'Enable'               ,'off' ...
                );
            
            % pushbutton 1_3 geometry
            
            c_ofs = 2*0.01+2*2*(0.05+0.01);
            r_ofs = 0.075;
            c_wth = 2*0.05;
            r_wth = 0.85;
            
            obj.amg.but1_3 = uicontrol(...
                'Parent'                ,obj.amg.hsp1 ...
                ,'Style'                ,'pushbutton' ...
                ,'String'               ,'close Cam.' ...
                ,'FontName'             ,Acquisition.Default_parameters.Pushbutton_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Pushbutton_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Pushbutton_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Pushbutton_FontWeight ...
                ,'Units'                ,Acquisition.Default_parameters.Pushbutton_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@obj.close_camera ...
                ,'Enable'               ,'off' ...
                );
            
            %%% Block sequence panel %%%
            
            c_ofs = 0.0025;
            r_ofs = 0.72;
            c_wth = 0.495;
            r_wth = 0.13;
            
            obj.amg.hsp2 = uipanel(...
                'Parent'              ,obj.amg.h ...
                ,'Title'              ,'Pixelfly Parameters' ...
                ,'TitlePosition'      ,'lefttop' ...
                ,'BackgroundColor'    ,Acquisition.Default_parameters.Panel_BackgroundColor ...
                ,'ForegroundColor'    ,Acquisition.Default_parameters.Panel_ForegroundColor ...
                ,'HighlightColor'     ,Acquisition.Default_parameters.Panel_HighlightColor ...
                ,'ShadowColor'        ,Acquisition.Default_parameters.Panel_ShadowColor ...
                ,'FontName'           ,Acquisition.Default_parameters.Panel_FontName ...
                ,'FontSize'           ,Acquisition.Default_parameters.Panel_FontSize ...
                ,'FontUnits'          ,Acquisition.Default_parameters.Panel_FontUnits ...
                ,'FontWeight'         ,Acquisition.Default_parameters.Panel_FontWeight ...
                ,'SelectionHighlight' ,Acquisition.Default_parameters.Panel_SelectionHighlight ...
                ,'Units'              ,Acquisition.Default_parameters.Panel_Units ...
                ,'Position'           ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % Text
            
            c_ofs = 0.01;
            r_ofs = 0.8;
            c_wth = 0.1;
            r_wth = 0.15;
            
            obj.amg.txt1_1 = uicontrol(...
                 'Parent'               ,obj.amg.hsp2 ...
                ,'Style'                ,'text' ...
                ,'String'               ,'Imaging Type :' ...
                ,'FontName'             ,Acquisition.Default_parameters.Text_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Text_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Text_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Text_FontWeight ...
                ,'HorizontalAlignment'  ,'left' ...
                ,'Units'                ,Acquisition.Default_parameters.Text_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % listbox
            
            c_ofs = 0.01;
            r_ofs = 0.1;
            c_wth = 0.1;
            r_wth = 0.65;
            
            obj.amg.lsb1_1 = uicontrol(...
                 'Parent'               ,obj.amg.hsp2 ...
                ,'Style'                ,'listbox' ...
                ,'Units'                , Acquisition.Default_parameters.Listbox_Units ...
                ,'String'               , Acquisition.Default_parameters.Pixelfly_imag_type ...
                ,'Value'                , Acquisition.Default_parameters.Pixelfly_imag_type_nbr ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@obj.amg_lsb1_clb ...
                );
            
            % Text
            
            c_ofs = 0.13;
            r_ofs = 0.8;
            c_wth = 0.08;
            r_wth = 0.15;
            
            obj.amg.txt1_2_1 = uicontrol(...
                 'Parent'               ,obj.amg.hsp2 ...
                ,'Style'                ,'text' ...
                ,'String'               ,'Expo. Time :' ...
                ,'FontName'             ,Acquisition.Default_parameters.Text_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Text_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Text_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Text_FontWeight ...
                ,'HorizontalAlignment'  ,Acquisition.Default_parameters.Text_HorizontalAlignment ...
                ,'Units'                ,Acquisition.Default_parameters.Text_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % Edit
            
            c_ofs = 0.215;
            r_ofs = 0.81;
            c_wth = 0.04;
            r_wth = 0.15;
            
            obj.amg.edt1_2 = uicontrol(...
                 'Parent'               ,obj.amg.hsp2 ...
                ,'Style'                ,'edit' ...
                ,'String'               ,'137' ...
                ,'Units'                ,Acquisition.Default_parameters.Edit_Units ...
                ,'FontName'             ,Acquisition.Default_parameters.Edit_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Edit_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Edit_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Edit_FontWeight ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth]...
                ,'Callback'             ,@obj.amg_edt1_2_clb ...
                );
            
            % Text
            
            c_ofs = 0.26;
            r_ofs = 0.8;
            c_wth = 0.02;
            r_wth = 0.15;
            
            obj.amg.txt1_2_2 = uicontrol(...
                 'Parent'               ,obj.amg.hsp2 ...
                ,'Style'                ,'text' ...
                ,'String'               ,'ms' ...
                ,'FontName'             ,Acquisition.Default_parameters.Text_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Text_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Text_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Text_FontWeight ...
                ,'HorizontalAlignment'  ,Acquisition.Default_parameters.Text_HorizontalAlignment ...
                ,'Units'                ,Acquisition.Default_parameters.Text_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % Text
            
            c_ofs = 0.132;
            r_ofs = 0.57;
            c_wth = 0.07;
            r_wth = 0.15;
            
            obj.amg.txt1_3_1 = uicontrol(...
                 'Parent'               ,obj.amg.hsp2 ...
                ,'Style'                ,'text' ...
                ,'String'               ,'Pixelclock :' ...
                ,'FontName'             ,Acquisition.Default_parameters.Text_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Text_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Text_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Text_FontWeight ...
                ,'HorizontalAlignment'  ,Acquisition.Default_parameters.Text_HorizontalAlignment ...
                ,'Units'                ,Acquisition.Default_parameters.Text_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % Popup
            
            c_ofs = 0.208;
            r_ofs = 0.51;
            c_wth = 0.04;
            r_wth = 0.25;
            
            obj.amg.popup1_3 = uicontrol(...
                'Parent'               ,obj.amg.hsp2 ...
                ,'Style'                ,'popup' ...
                ,'String'               ,'12|25' ...
                ,'FontName'             ,Acquisition.Default_parameters.Popup_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Popup_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Popup_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Popup_FontWeight ...
                ,'Units'                ,Acquisition.Default_parameters.Popup_Units ...
                ,'Value'                ,Acquisition.Default_parameters.Pixelclock ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth]...
                ,'Callback'             ,@obj.amg_popup1_3_clb ...
                );
            
            % Text
            
            c_ofs = 0.253;
            r_ofs = 0.57;
            c_wth = 0.08;
            r_wth = 0.15;
            
            obj.amg.txt1_3_2 = uicontrol(...
                 'Parent'               ,obj.amg.hsp2 ...
                ,'Style'                ,'text' ...
                ,'String'               ,'x1e6 Pixels/s' ... 
                ,'FontName'             ,Acquisition.Default_parameters.Text_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Text_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Text_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Text_FontWeight ...
                ,'HorizontalAlignment'  ,Acquisition.Default_parameters.Text_HorizontalAlignment ...
                ,'Units'                ,Acquisition.Default_parameters.Text_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % Text
            
            c_ofs = 0.13;
            r_ofs = 0.33;
            c_wth = 0.08;
            r_wth = 0.15;
            
            obj.amg.txt1_4_1 = uicontrol(...
                 'Parent'               ,obj.amg.hsp2 ...
                ,'Style'                ,'text' ...
                ,'String'               ,'Conv. factor :' ...
                ,'FontName'             ,Acquisition.Default_parameters.Text_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Text_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Text_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Text_FontWeight ...
                ,'HorizontalAlignment'  ,Acquisition.Default_parameters.Text_HorizontalAlignment ...
                ,'Units'                ,Acquisition.Default_parameters.Text_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % Edit
            
            c_ofs = 0.215;
            r_ofs = 0.34;
            c_wth = 0.04;
            r_wth = 0.15;
            
            obj.amg.edt1_4 = uicontrol(...
                 'Parent'               ,obj.amg.hsp2 ...
                ,'Style'                ,'edit' ...
                ,'String'               ,num2str(Acquisition.Default_parameters.Conv_factor) ...
                ,'Units'                ,Acquisition.Default_parameters.Edit_Units ...
                ,'FontName'             ,Acquisition.Default_parameters.Edit_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Edit_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Edit_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Edit_FontWeight ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth]...
                ,'Callback'             ,@obj.amg_edt1_4_clb ...
                );
            
        end
        
        function init_cam(obj,~,~)
            
            obj.pixelfly = Pixelfly.PixelflyClass();
            
            obj.amg_lsb1_clb;
            
            set(obj.amg.but1_2,'Enable','on');
            
            set(obj.amg.but1_1,'Enable','off');
            
        end
        
        function start_acquisition(obj,~,~)
            
            switch obj.running
                
                case 0
                    
                    % initialize and start camera
                    
                    obj.pixelfly.StartAcquisition(); % Call the methods to prepare the camera for the acquisition
                    
                    set(obj.amg.but1_2,'BackgroundColor',[1.0,0.0,0.0]);
                    set(obj.amg.but1_2,'String','stop Acquis.');
                    
                    set(obj.amg.but1_3,'Enable','off');
                    
                    obj.running = 1;
                    
                case 1
                    
                    % stop camera
                    
                    obj.pixelfly.StopAcquisition();  % Close the camera and clear the memory
                    
                    set(obj.amg.but1_2,'BackgroundColor',[0.0,1.0,0.0]);
                    set(obj.amg.but1_2,'String','start Acquis.');
                    
                    set(obj.amg.but1_3,'Enable','on');
                    
                    obj.running = 0;
                    
            end
            
        end
        
        function close_camera(obj,~,~)
            
            %delete(obj.pixelfly.imgTimer);
            
            obj.pixelfly = [];
            
            set(obj.amg.but1_1,'Enable','on');
            set(obj.amg.but1_2,'Enable','off');
            set(obj.amg.but1_3,'Enable','off');
            
        end
        
        function amg_lsb1_clb(obj,~,~)
            
            list_cell = get(obj.amg.lsb1_1,'String');
            
            ind = get(obj.amg.lsb1_1,'Value');
            
            obj.pixelfly.imagingType = list_cell{ind};
            
        end
        
        function amg_edt1_2_clb(obj,~,~)
            
        end
        
        function amg_popup1_3_clb(obj,~,~)
            
        end
        
        function amg_edt1_4_clb(obj,~,~)
            
        end
        
        function execute(obj,name,message)
            
            switch name
                
                case 'BEC008'
                    
                    isAcqDone = obj.pixelfly.GetImages;
                    
                    % pause(2.5);
                    
                    if( isAcqDone )
                        disp('images ready');
                        obj.net.send_message('main',message);
                    end
                    
            end
            
        end
        
        function delete(obj)
           
            delete(obj.net);
            
        end

    end
    
    
    
end