classdef Acquisition_dual < handle
    % Acquisition class
    
    properties % GUI
        
        amg % acquisition main GUI
        
    end
    
    properties

        % Class for the Pixelfly camera
        
        pixelfly;
        pixelfly_running = 0;
        
        % Class for the ImagingSource camera
        
        imagingsource;  
        imagingsource_running = 0;
        
        % Class for Tabor WW2571A
        
        tabor;
        
        % Class for R&S SMC100A
        
        smc100a;
        
    end
    
    properties
        
        net
        
    end
    
    methods
        
        function obj = Acquisition_dual()
            
            obj = obj@handle;
            
            % create Network class
            
            obj.net = Network.Network(obj);
            
            % create Tabor class
            
            obj.tabor = Tabor.TaborClass();
            
            obj.tabor.parent = obj;
            
            % create Pixelfly class
            
            obj.pixelfly = Pixelfly.PixelflyClass();
            
            obj.pixelfly.parent = obj;
            
            % create ImagingSource class
  
            imaqreset % reset 
            
            obj.imagingsource = ImagSource.ImagSourceClass();
            
            obj.imagingsource.parent = obj;
            
            % create SMC100A class
            
            obj.smc100a = SMC100A.SMC100AClass();
            
            obj.smc100a.parent = obj;

        end
        
        function acquisition_main_gui(obj)
            
            % initialize Vision GUI
            
            obj.amg.h = figure(...
                'Name'                ,'Acquisition Main' ...
                ,'NumberTitle'        ,'off' ...
                ,'Position'           ,[8 48 1904 950] ... %,'MenuBar'     ,'none'...
                );
            
            %%% Block sequence panel %%%
            
            c_ofs = 0.0025;
            r_ofs = 0.86;
            c_wth = 0.495;
            r_wth = 0.13;
            
            obj.amg.hsp1 = uipanel(...
                'Parent'              ,obj.amg.h ...
                ,'Title'              ,'Pixelfly Control' ...
                ,'TitlePosition'      ,'lefttop' ...
                ,'BackgroundColor'    ,Acquisition.Default_parameters.Panel_BackgroundColor ...
                ,'ForegroundColor'    ,Acquisition.Default_parameters.Panel_ForegroundColor ...
                ,'HighlightColor'     ,Acquisition.Default_parameters.Panel_HighlightColor ...
                ,'ShadowColor'        ,Acquisition.Default_parameters.Panel_ShadowColor ...
                ,'FontName'           ,Acquisition.Default_parameters.Panel_FontName ...
                ,'FontSize'           ,Acquisition.Default_parameters.Panel_FontSize ...
                ,'FontUnits'          ,Acquisition.Default_parameters.Panel_FontUnits ...
                ,'FontWeight'         ,Acquisition.Default_parameters.Panel_FontWeight ...
                ,'SelectionHighlight' ,Acquisition.Default_parameters.Panel_SelectionHighlight ...
                ,'Units'              ,Acquisition.Default_parameters.Panel_Units ...
                ,'Position'           ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % pushbutton 1_1 geometry
            
            c_ofs = 2*0.01;
            r_ofs = 0.075;
            c_wth = 2*0.05;
            r_wth = 0.85;
            
            obj.amg.but1_1 = uicontrol(...
                'Parent'                ,obj.amg.hsp1 ...
                ,'Style'                ,'pushbutton' ...
                ,'String'               ,'init. Cam.' ...
                ,'FontName'             ,Acquisition.Default_parameters.Pushbutton_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Pushbutton_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Pushbutton_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Pushbutton_FontWeight ...
                ,'Units'                ,Acquisition.Default_parameters.Pushbutton_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@obj.init_pixelfly ...
                );
            
            % pushbutton 1_2 geometry
            
            c_ofs = 2*0.01+2*(0.05+0.01);
            r_ofs = 0.075;
            c_wth = 2*0.05;
            r_wth = 0.85;
            
            obj.amg.but1_2 = uicontrol(...
                'Parent'                ,obj.amg.hsp1 ...
                ,'Style'                ,'pushbutton' ...
                ,'String'               ,'start Acquis.' ...
                ,'FontName'             ,Acquisition.Default_parameters.Pushbutton_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Pushbutton_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Pushbutton_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Pushbutton_FontWeight ...
                ,'Units'                ,Acquisition.Default_parameters.Pushbutton_Units ...
                ,'BackgroundColor'      ,[0.0 1.0 0.0] ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@obj.start_acquisition ...
                ,'Enable'               ,'off' ...
                );
            
            % pushbutton 1_3 geometry
            
            c_ofs = 2*0.01+2*2*(0.05+0.01);
            r_ofs = 0.075;
            c_wth = 2*0.05;
            r_wth = 0.85;
            
            obj.amg.but1_3 = uicontrol(...
                'Parent'                ,obj.amg.hsp1 ...
                ,'Style'                ,'pushbutton' ...
                ,'String'               ,'close Cam.' ...
                ,'FontName'             ,Acquisition.Default_parameters.Pushbutton_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Pushbutton_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Pushbutton_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Pushbutton_FontWeight ...
                ,'Units'                ,Acquisition.Default_parameters.Pushbutton_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@obj.close_camera ...
                ,'Enable'               ,'off' ...
                );
            
            %%% Block sequence panel %%%
            
            c_ofs = 0.0025;
            r_ofs = 0.72;
            c_wth = 0.495;
            r_wth = 0.13;
            
            obj.amg.hsp2 = uipanel(...
                'Parent'              ,obj.amg.h ...
                ,'Title'              ,'Pixelfly Parameters' ...
                ,'TitlePosition'      ,'lefttop' ...
                ,'BackgroundColor'    ,Acquisition.Default_parameters.Panel_BackgroundColor ...
                ,'ForegroundColor'    ,Acquisition.Default_parameters.Panel_ForegroundColor ...
                ,'HighlightColor'     ,Acquisition.Default_parameters.Panel_HighlightColor ...
                ,'ShadowColor'        ,Acquisition.Default_parameters.Panel_ShadowColor ...
                ,'FontName'           ,Acquisition.Default_parameters.Panel_FontName ...
                ,'FontSize'           ,Acquisition.Default_parameters.Panel_FontSize ...
                ,'FontUnits'          ,Acquisition.Default_parameters.Panel_FontUnits ...
                ,'FontWeight'         ,Acquisition.Default_parameters.Panel_FontWeight ...
                ,'SelectionHighlight' ,Acquisition.Default_parameters.Panel_SelectionHighlight ...
                ,'Units'              ,Acquisition.Default_parameters.Panel_Units ...
                ,'Position'           ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % Text
            
            c_ofs = 0.01;
            r_ofs = 0.8;
            c_wth = 0.1;
            r_wth = 0.15;
            
            obj.amg.txt1_1 = uicontrol(...
                'Parent'               ,obj.amg.hsp2 ...
                ,'Style'                ,'text' ...
                ,'String'               ,'Imaging Type :' ...
                ,'FontName'             ,Acquisition.Default_parameters.Text_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Text_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Text_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Text_FontWeight ...
                ,'HorizontalAlignment'  ,'left' ...
                ,'Units'                ,Acquisition.Default_parameters.Text_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % listbox
            
            c_ofs = 0.01;
            r_ofs = 0.1;
            c_wth = 0.1;
            r_wth = 0.65;
            
            obj.amg.lsb1_1 = uicontrol(...
                'Parent'               ,obj.amg.hsp2 ...
                ,'Style'                ,'listbox' ...
                ,'Units'                , Acquisition.Default_parameters.Listbox_Units ...
                ,'String'               , Acquisition.Default_parameters.Pixelfly_imag_type ...
                ,'Value'                , Acquisition.Default_parameters.Pixelfly_imag_type_nbr ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@obj.amg_lsb1_clb ...
                );
            
            % Text
            
            c_ofs = 0.13;
            r_ofs = 0.8;
            c_wth = 0.08;
            r_wth = 0.15;
            
            obj.amg.txt1_2_1 = uicontrol(...
                'Parent'               ,obj.amg.hsp2 ...
                ,'Style'                ,'text' ...
                ,'String'               ,'Expo. Time :' ...
                ,'FontName'             ,Acquisition.Default_parameters.Text_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Text_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Text_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Text_FontWeight ...
                ,'HorizontalAlignment'  ,Acquisition.Default_parameters.Text_HorizontalAlignment ...
                ,'Units'                ,Acquisition.Default_parameters.Text_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % Edit
            
            c_ofs = 0.215;
            r_ofs = 0.81;
            c_wth = 0.04;
            r_wth = 0.15;
            
            obj.amg.edt1_2 = uicontrol(...
                'Parent'               ,obj.amg.hsp2 ...
                ,'Style'                ,'edit' ...
                ,'String'               ,'137' ...
                ,'Units'                ,Acquisition.Default_parameters.Edit_Units ...
                ,'FontName'             ,Acquisition.Default_parameters.Edit_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Edit_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Edit_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Edit_FontWeight ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth]...
                ,'Callback'             ,@obj.amg_edt1_2_clb ...
                );
            
            % Text
            
            c_ofs = 0.26;
            r_ofs = 0.8;
            c_wth = 0.04;
            r_wth = 0.15;
            
            obj.amg.txt1_2_2 = uicontrol(...
                'Parent'               ,obj.amg.hsp2 ...
                ,'Style'                ,'text' ...
                ,'String'               ,'ms' ...
                ,'FontName'             ,Acquisition.Default_parameters.Text_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Text_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Text_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Text_FontWeight ...
                ,'HorizontalAlignment'  ,Acquisition.Default_parameters.Text_HorizontalAlignment ...
                ,'Units'                ,Acquisition.Default_parameters.Text_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % Text
            
            c_ofs = 0.132;
            r_ofs = 0.57;
            c_wth = 0.07;
            r_wth = 0.15;
            
            obj.amg.txt1_3_1 = uicontrol(...
                'Parent'               ,obj.amg.hsp2 ...
                ,'Style'                ,'text' ...
                ,'String'               ,'Pixelclock :' ...
                ,'FontName'             ,Acquisition.Default_parameters.Text_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Text_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Text_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Text_FontWeight ...
                ,'HorizontalAlignment'  ,Acquisition.Default_parameters.Text_HorizontalAlignment ...
                ,'Units'                ,Acquisition.Default_parameters.Text_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % Popup
            
            c_ofs = 0.208;
            r_ofs = 0.51;
            c_wth = 0.04;
            r_wth = 0.25;
            
            obj.amg.popup1_3 = uicontrol(...
                'Parent'               ,obj.amg.hsp2 ...
                ,'Style'                ,'popup' ...
                ,'String'               ,'12|25' ...
                ,'FontName'             ,Acquisition.Default_parameters.Popup_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Popup_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Popup_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Popup_FontWeight ...
                ,'Units'                ,Acquisition.Default_parameters.Popup_Units ...
                ,'Value'                ,Acquisition.Default_parameters.Pixelclock ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth]...
                ,'Callback'             ,@obj.amg_popup1_3_clb ...
                );
            
            % Text
            
            c_ofs = 0.253;
            r_ofs = 0.57;
            c_wth = 0.08;
            r_wth = 0.15;
            
            obj.amg.txt1_3_2 = uicontrol(...
                'Parent'               ,obj.amg.hsp2 ...
                ,'Style'                ,'text' ...
                ,'String'               ,'x1e6 Pixels/s' ...
                ,'FontName'             ,Acquisition.Default_parameters.Text_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Text_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Text_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Text_FontWeight ...
                ,'HorizontalAlignment'  ,Acquisition.Default_parameters.Text_HorizontalAlignment ...
                ,'Units'                ,Acquisition.Default_parameters.Text_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % Text
            
            c_ofs = 0.13;
            r_ofs = 0.33;
            c_wth = 0.08;
            r_wth = 0.15;
            
            obj.amg.txt1_4_1 = uicontrol(...
                'Parent'               ,obj.amg.hsp2 ...
                ,'Style'                ,'text' ...
                ,'String'               ,'Conv. factor :' ...
                ,'FontName'             ,Acquisition.Default_parameters.Text_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Text_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Text_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Text_FontWeight ...
                ,'HorizontalAlignment'  ,Acquisition.Default_parameters.Text_HorizontalAlignment ...
                ,'Units'                ,Acquisition.Default_parameters.Text_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % Edit
            
            c_ofs = 0.215;
            r_ofs = 0.34;
            c_wth = 0.04;
            r_wth = 0.15;
            
            obj.amg.edt1_4 = uicontrol(...
                'Parent'               ,obj.amg.hsp2 ...
                ,'Style'                ,'edit' ...
                ,'String'               ,num2str(Acquisition.Default_parameters.Conv_factor) ...
                ,'Units'                ,Acquisition.Default_parameters.Edit_Units ...
                ,'FontName'             ,Acquisition.Default_parameters.Edit_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Edit_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Edit_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Edit_FontWeight ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth]...
                ,'Callback'             ,@obj.amg_edt1_4_clb ...
                );
            %%% Block sequence panel %%%
            
            c_ofs = 0.0025;
            r_ofs = 0.58;
            c_wth = 0.495;
            r_wth = 0.13;
            
            obj.amg.hsp3 = uipanel(...
                'Parent'              ,obj.amg.h ...
                ,'Title'              ,'ImagingSource Control' ...
                ,'TitlePosition'      ,'lefttop' ...
                ,'BackgroundColor'    ,Acquisition.Default_parameters.Panel_BackgroundColor ...
                ,'ForegroundColor'    ,Acquisition.Default_parameters.Panel_ForegroundColor ...
                ,'HighlightColor'     ,Acquisition.Default_parameters.Panel_HighlightColor ...
                ,'ShadowColor'        ,Acquisition.Default_parameters.Panel_ShadowColor ...
                ,'FontName'           ,Acquisition.Default_parameters.Panel_FontName ...
                ,'FontSize'           ,Acquisition.Default_parameters.Panel_FontSize ...
                ,'FontUnits'          ,Acquisition.Default_parameters.Panel_FontUnits ...
                ,'FontWeight'         ,Acquisition.Default_parameters.Panel_FontWeight ...
                ,'SelectionHighlight' ,Acquisition.Default_parameters.Panel_SelectionHighlight ...
                ,'Units'              ,Acquisition.Default_parameters.Panel_Units ...
                ,'Position'           ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % pushbutton 3_1 geometry
            
            c_ofs = 2*0.01;
            r_ofs = 0.075;
            c_wth = 2*0.05;
            r_wth = 0.85;
            
            obj.amg.but3_1 = uicontrol(...
                'Parent'                ,obj.amg.hsp3 ...
                ,'Style'                ,'pushbutton' ...
                ,'String'               ,'init. Cam.' ...
                ,'FontName'             ,Acquisition.Default_parameters.Pushbutton_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Pushbutton_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Pushbutton_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Pushbutton_FontWeight ...
                ,'Units'                ,Acquisition.Default_parameters.Pushbutton_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@obj.init_imagingsource ...
                );
            
            % pushbutton 3_2 geometry
            
            c_ofs = 2*0.01+2*(0.05+0.01);
            r_ofs = 0.075;
            c_wth = 2*0.05;
            r_wth = 0.85;
            
            obj.amg.but3_2 = uicontrol(...
                'Parent'                ,obj.amg.hsp3 ...
                ,'Style'                ,'pushbutton' ...
                ,'String'               ,'start Acquis.' ...
                ,'FontName'             ,Acquisition.Default_parameters.Pushbutton_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Pushbutton_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Pushbutton_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Pushbutton_FontWeight ...
                ,'Units'                ,Acquisition.Default_parameters.Pushbutton_Units ...
                ,'BackgroundColor'      ,[0.0 1.0 0.0] ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@obj.start_acquisition2 ...
                ,'Enable'               ,'off' ...
                );
            
            % pushbutton 3_3 geometry
            
            c_ofs = 2*0.01+2*2*(0.05+0.01);
            r_ofs = 0.075;
            c_wth = 2*0.05;
            r_wth = 0.85;
            
            obj.amg.but3_3 = uicontrol(...
                'Parent'                ,obj.amg.hsp3 ...
                ,'Style'                ,'pushbutton' ...
                ,'String'               ,'close Cam.' ...
                ,'FontName'             ,Acquisition.Default_parameters.Pushbutton_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Pushbutton_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Pushbutton_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Pushbutton_FontWeight ...
                ,'Units'                ,Acquisition.Default_parameters.Pushbutton_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@obj.close_camera2 ...
                ,'Enable'               ,'off' ...
                );
            
            %%% Block sequence panel %%%
            
            c_ofs = 0.0025;
            r_ofs = 0.44;
            c_wth = 0.495;
            r_wth = 0.13;
            
            obj.amg.hsp4 = uipanel(...
                'Parent'              ,obj.amg.h ...
                ,'Title'              ,'ImagingSource Parameters' ...
                ,'TitlePosition'      ,'lefttop' ...
                ,'BackgroundColor'    ,Acquisition.Default_parameters.Panel_BackgroundColor ...
                ,'ForegroundColor'    ,Acquisition.Default_parameters.Panel_ForegroundColor ...
                ,'HighlightColor'     ,Acquisition.Default_parameters.Panel_HighlightColor ...
                ,'ShadowColor'        ,Acquisition.Default_parameters.Panel_ShadowColor ...
                ,'FontName'           ,Acquisition.Default_parameters.Panel_FontName ...
                ,'FontSize'           ,Acquisition.Default_parameters.Panel_FontSize ...
                ,'FontUnits'          ,Acquisition.Default_parameters.Panel_FontUnits ...
                ,'FontWeight'         ,Acquisition.Default_parameters.Panel_FontWeight ...
                ,'SelectionHighlight' ,Acquisition.Default_parameters.Panel_SelectionHighlight ...
                ,'Units'              ,Acquisition.Default_parameters.Panel_Units ...
                ,'Position'           ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % pushbutton 4_1 geometry
            
            c_ofs = 2*0.01;
            r_ofs = 0.075;
            c_wth = 2*0.05;
            r_wth = 0.85;
            
            temp = obj.imagingsource;
            
            obj.amg.but4_1 = uicontrol(...
                'Parent'                ,obj.amg.hsp4 ...
                ,'Style'                ,'pushbutton' ...
                ,'String'               ,'Reset Settings' ...
                ,'FontName'             ,Acquisition.Default_parameters.Pushbutton_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Pushbutton_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Pushbutton_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Pushbutton_FontWeight ...
                ,'Units'                ,Acquisition.Default_parameters.Pushbutton_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@temp.set_default_params ...
                ,'Enable'               ,'off' ...
                );
            
            clear temp
            
            %                                       % pushbutton 4_2 geometry
            %
            %                                         c_ofs = 2*0.01+2*(0.05+0.01);
            %                                         r_ofs = 0.075;
            %                                         c_wth = 2*0.05;
            %                                         r_wth = 0.85;
            %
            %                                         obj.amg.but3_2 = uicontrol(...
            %                                             'Parent'                ,obj.amg.hsp3 ...
            %                                             ,'Style'                ,'pushbutton' ...
            %                                             ,'String'               ,'start Acquis.' ...
            %                                             ,'FontName'             ,Acquisition.Default_parameters.Pushbutton_FontName ...
            %                                             ,'FontSize'             ,Acquisition.Default_parameters.Pushbutton_FontSize ...
            %                                             ,'FontUnits'            ,Acquisition.Default_parameters.Pushbutton_FontUnits ...
            %                                             ,'FontWeight'           ,Acquisition.Default_parameters.Pushbutton_FontWeight ...
            %                                             ,'Units'                ,Acquisition.Default_parameters.Pushbutton_Units ...
            %                                             ,'BackgroundColor'      ,[0.0 1.0 0.0] ...
            %                                             ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
            %                                             ,'Callback'             ,@obj.Preview ...
            %                                             ,'Enable'               ,'off' ...
            %                                             );
            
            %    Could add buttons for the command 'inpect(vid/src)'
            %
            % Text
            
            c_ofs = 2*0.01+2*(0.05+0.01);
            r_ofs = 0.8;
            c_wth = 0.1;
            r_wth = 0.15;
            
            obj.amg.txt4_1 = uicontrol(...
                'Parent'               ,obj.amg.hsp4 ...
                ,'Style'                ,'text' ...
                ,'String'               ,'Imaging Type :' ...
                ,'FontName'             ,Acquisition.Default_parameters.Text_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Text_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Text_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Text_FontWeight ...
                ,'HorizontalAlignment'  ,'left' ...
                ,'Units'                ,Acquisition.Default_parameters.Text_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % listbox
            
            c_ofs = 2*0.01+2*(0.05+0.01);
            r_ofs = 0.075;
            c_wth = 0.1;
            r_wth = 0.65;
            
            obj.amg.lsb4_1 = uicontrol(...
                'Parent'               ,obj.amg.hsp4 ...
                ,'Style'                ,'listbox' ...
                ,'Units'                , Acquisition.Default_parameters.Listbox_Units ...
                ,'String'               , Acquisition.Default_parameters.ImagingSource_imag_type ...
                ,'Value'                , Acquisition.Default_parameters.ImagingSource_imag_type_nbr ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@obj.amg_lsb2_clb ...
                );
            
            
            c_ofs = 2*0.01+2*2*(0.05+0.01);
            r_ofs = 0.075;
            c_wth = 2*0.05;
            r_wth = 0.85;
            
            temp = obj.imagingsource;
            
            obj.amg.but4_3 = uicontrol(...
                'Parent'                ,obj.amg.hsp4 ...
                ,'Style'                ,'pushbutton' ...
                ,'String'               ,'Inspect Vid' ...
                ,'FontName'             ,Acquisition.Default_parameters.Pushbutton_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Pushbutton_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Pushbutton_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Pushbutton_FontWeight ...
                ,'Units'                ,Acquisition.Default_parameters.Pushbutton_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@temp.InspectVid ...
                ,'Enable'               ,'off' ...
                );
            
            clear temp
            
            c_ofs = 3*0.01+3*2*(0.05+0.01);
            r_ofs = 0.075;
            c_wth = 2*0.05;
            r_wth = 0.85;
            
            temp = obj.imagingsource;
            
            obj.amg.but4_4 = uicontrol(...
                'Parent'                ,obj.amg.hsp4 ...
                ,'Style'                ,'pushbutton' ...
                ,'String'               ,'Inspect Src' ...
                ,'FontName'             ,Acquisition.Default_parameters.Pushbutton_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Pushbutton_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Pushbutton_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Pushbutton_FontWeight ...
                ,'Units'                ,Acquisition.Default_parameters.Pushbutton_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@temp.InspectSrc ...
                ,'Enable'               ,'off' ...
                );
            
            clear temp
            
            c_ofs = 4*0.01+4*2*(0.05+0.01);
            r_ofs = 0.075;
            c_wth = 2*0.05;
            r_wth = 0.85;
            
            temp = obj.imagingsource; 
            
            obj.amg.but4_5 = uicontrol(...
                'Parent'                ,obj.amg.hsp4 ...
                ,'Style'                ,'pushbutton' ...
                ,'String'               ,'Preview Vid' ...
                ,'FontName'             ,Acquisition.Default_parameters.Pushbutton_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Pushbutton_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Pushbutton_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Pushbutton_FontWeight ...
                ,'Units'                ,Acquisition.Default_parameters.Pushbutton_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@temp.preview_camera2 ...
                ,'Enable'               ,'off' ...
                );
            
            clear temp
            
            %%% Block sequence panel %%%
            
            c_ofs = 0.0025;
            r_ofs = 0.30;
            c_wth = 0.495;
            r_wth = 0.13;
            
            obj.amg.hsp5 = uipanel(...
                'Parent'              ,obj.amg.h ...
                ,'Title'              ,'Tabor Control' ...
                ,'TitlePosition'      ,'lefttop' ...
                ,'BackgroundColor'    ,Acquisition.Default_parameters.Panel_BackgroundColor ...
                ,'ForegroundColor'    ,Acquisition.Default_parameters.Panel_ForegroundColor ...
                ,'HighlightColor'     ,Acquisition.Default_parameters.Panel_HighlightColor ...
                ,'ShadowColor'        ,Acquisition.Default_parameters.Panel_ShadowColor ...
                ,'FontName'           ,Acquisition.Default_parameters.Panel_FontName ...
                ,'FontSize'           ,Acquisition.Default_parameters.Panel_FontSize ...
                ,'FontUnits'          ,Acquisition.Default_parameters.Panel_FontUnits ...
                ,'FontWeight'         ,Acquisition.Default_parameters.Panel_FontWeight ...
                ,'SelectionHighlight' ,Acquisition.Default_parameters.Panel_SelectionHighlight ...
                ,'Units'              ,Acquisition.Default_parameters.Panel_Units ...
                ,'Position'           ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % pushbutton 5_1 geometry
            
            c_ofs = 2*0.01;
            r_ofs = 0.075;
            c_wth = 2*0.05;
            r_wth = 0.85;
            
            obj.amg.but5_1 = uicontrol(...
                'Parent'                ,obj.amg.hsp5 ...
                ,'Style'                ,'pushbutton' ...
                ,'String'               ,'init. Tabor' ...
                ,'FontName'             ,Acquisition.Default_parameters.Pushbutton_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Pushbutton_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Pushbutton_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Pushbutton_FontWeight ...
                ,'Units'                ,Acquisition.Default_parameters.Pushbutton_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@obj.init_Tabor ...
                );
            
            % pushbutton 5_2 geometry
            
            c_ofs = 2*0.01+2*(0.05+0.01);
            r_ofs = 0.075;
            c_wth = 2*0.05;
            r_wth = 0.85;
            
            obj.amg.but5_2 = uicontrol(...
                'Parent'                ,obj.amg.hsp5 ...
                ,'Style'                ,'pushbutton' ...
                ,'String'               ,'close Tabor' ...
                ,'FontName'             ,Acquisition.Default_parameters.Pushbutton_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Pushbutton_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Pushbutton_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Pushbutton_FontWeight ...
                ,'Units'                ,Acquisition.Default_parameters.Pushbutton_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@obj.close_Tabor ...
                ,'Enable'               ,'off' ...
                );
            
            %%% Block sequence panel %%%
            
            c_ofs = 0.0025;
            r_ofs = 0.16;
            c_wth = 0.495;
            r_wth = 0.13;
 
            obj.amg.hsp6 = uipanel(...
                'Parent'              ,obj.amg.h ...
                ,'Title'              ,'Tabor Parameters' ...
                ,'TitlePosition'      ,'lefttop' ...
                ,'BackgroundColor'    ,Acquisition.Default_parameters.Panel_BackgroundColor ...
                ,'ForegroundColor'    ,Acquisition.Default_parameters.Panel_ForegroundColor ...
                ,'HighlightColor'     ,Acquisition.Default_parameters.Panel_HighlightColor ...
                ,'ShadowColor'        ,Acquisition.Default_parameters.Panel_ShadowColor ...
                ,'FontName'           ,Acquisition.Default_parameters.Panel_FontName ...
                ,'FontSize'           ,Acquisition.Default_parameters.Panel_FontSize ...
                ,'FontUnits'          ,Acquisition.Default_parameters.Panel_FontUnits ...
                ,'FontWeight'         ,Acquisition.Default_parameters.Panel_FontWeight ...
                ,'SelectionHighlight' ,Acquisition.Default_parameters.Panel_SelectionHighlight ...
                ,'Units'              ,Acquisition.Default_parameters.Panel_Units ...
                ,'Position'           ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % pushbutton 6_1 geometry
            
            c_ofs = 2*0.01;
            r_ofs = 0.075;
            c_wth = 2*0.05;
            r_wth = 0.85;
            
            temp = obj.tabor;
            
            obj.amg.but6_1 = uicontrol(...
                'Parent'                ,obj.amg.hsp6 ...
                ,'Style'                ,'pushbutton' ...
                ,'String'               ,'Load Waves' ...
                ,'FontName'             ,Acquisition.Default_parameters.Pushbutton_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Pushbutton_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Pushbutton_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Pushbutton_FontWeight ...
                ,'Units'                ,Acquisition.Default_parameters.Pushbutton_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@temp.load_waves ...
                ,'Enable'               ,'off' ...
                );
            
            clear temp
            
            % Text
            
            c_ofs = 0.13;
            r_ofs = 0.75;
            c_wth = 0.2;
            r_wth = 0.15;
            
            obj.amg.txt6_1 = uicontrol(...
                'Parent'               ,obj.amg.hsp6 ...
                ,'Style'                ,'text' ...
                ,'String'               ,strcat('Sample rate : ',num2str(Tabor.Default_parameters.sample_rate/1e6),' MHz') ...
                ,'FontName'             ,Acquisition.Default_parameters.Text_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Text_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Text_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Text_FontWeight ...
                ,'HorizontalAlignment'  ,Acquisition.Default_parameters.Text_HorizontalAlignment ...
                ,'Units'                ,Acquisition.Default_parameters.Text_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
           % Text
            
            c_ofs = 0.13;
            r_ofs = 0.5;
            c_wth = 0.2;
            r_wth = 0.15;
            
            obj.amg.txt6_2 = uicontrol(...
                'Parent'               ,obj.amg.hsp6 ...
                ,'Style'                ,'text' ...
                ,'String'               ,strcat('Gain : ',num2str(Tabor.Default_parameters.gain),'    Offset : ',num2str(Tabor.Default_parameters.offset)) ...
                ,'FontName'             ,Acquisition.Default_parameters.Text_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Text_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Text_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Text_FontWeight ...
                ,'HorizontalAlignment'  ,Acquisition.Default_parameters.Text_HorizontalAlignment ...
                ,'Units'                ,Acquisition.Default_parameters.Text_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            
            % Text
            
            c_ofs = 0.13;
            r_ofs = 0.25;
            c_wth = 0.2;
            r_wth = 0.15;
            
            if Tabor.Default_parameters.filter == 0
                msg = 'None';
                
            elseif Tabor.Default_parameters.filter == 1
                    msg = '25 MHz';
                    
            elseif Tabor.Default_parameters.filter == 2
                    msg = '50 MHz';        
                
            elseif Tabor.Default_parameters.filter == 3
                    msg = '60 MHz';
                    
            elseif Tabor.Default_parameters.filter == 4
                    msg = '120 MHz';
            end
                
            obj.amg.txt6_3 = uicontrol(...
                'Parent'               ,obj.amg.hsp6 ...
                ,'Style'                ,'text' ...
                ,'String'               ,strcat('Filter : ',msg) ...
                ,'FontName'             ,Acquisition.Default_parameters.Text_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Text_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Text_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Text_FontWeight ...
                ,'HorizontalAlignment'  ,Acquisition.Default_parameters.Text_HorizontalAlignment ...
                ,'Units'                ,Acquisition.Default_parameters.Text_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            %%% Block sequence panel %%%
            
            c_ofs = 0.5025;
            r_ofs = 0.86;
            c_wth = 0.495;
            r_wth = 0.13;
            
            obj.amg.hsp7 = uipanel(...
                'Parent'              ,obj.amg.h ...
                ,'Title'              ,'R&S Control' ...
                ,'TitlePosition'      ,'lefttop' ...
                ,'BackgroundColor'    ,Acquisition.Default_parameters.Panel_BackgroundColor ...
                ,'ForegroundColor'    ,Acquisition.Default_parameters.Panel_ForegroundColor ...
                ,'HighlightColor'     ,Acquisition.Default_parameters.Panel_HighlightColor ...
                ,'ShadowColor'        ,Acquisition.Default_parameters.Panel_ShadowColor ...
                ,'FontName'           ,Acquisition.Default_parameters.Panel_FontName ...
                ,'FontSize'           ,Acquisition.Default_parameters.Panel_FontSize ...
                ,'FontUnits'          ,Acquisition.Default_parameters.Panel_FontUnits ...
                ,'FontWeight'         ,Acquisition.Default_parameters.Panel_FontWeight ...
                ,'SelectionHighlight' ,Acquisition.Default_parameters.Panel_SelectionHighlight ...
                ,'Units'              ,Acquisition.Default_parameters.Panel_Units ...
                ,'Position'           ,[c_ofs r_ofs c_wth r_wth] ...
                );
            
            % pushbutton 7_1 geometry
            
            c_ofs = 2*0.01;
            r_ofs = 0.075;
            c_wth = 2*0.05;
            r_wth = 0.85;
            
            obj.amg.but7_1 = uicontrol(...
                'Parent'                ,obj.amg.hsp7 ...
                ,'Style'                ,'pushbutton' ...
                ,'String'               ,'init. R&S' ...
                ,'FontName'             ,Acquisition.Default_parameters.Pushbutton_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Pushbutton_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Pushbutton_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Pushbutton_FontWeight ...
                ,'Units'                ,Acquisition.Default_parameters.Pushbutton_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@obj.init_smc100a ...
                );
            
            % pushbutton 7_2 geometry
            
            c_ofs = 2*0.01+2*(0.05+0.01);
            r_ofs = 0.075;
            c_wth = 2*0.05;
            r_wth = 0.85;
            
            obj.amg.but7_2 = uicontrol(...
                'Parent'                ,obj.amg.hsp7 ...
                ,'Style'                ,'pushbutton' ...
                ,'String'               ,'close R&S' ...
                ,'FontName'             ,Acquisition.Default_parameters.Pushbutton_FontName ...
                ,'FontSize'             ,Acquisition.Default_parameters.Pushbutton_FontSize ...
                ,'FontUnits'            ,Acquisition.Default_parameters.Pushbutton_FontUnits ...
                ,'FontWeight'           ,Acquisition.Default_parameters.Pushbutton_FontWeight ...
                ,'Units'                ,Acquisition.Default_parameters.Pushbutton_Units ...
                ,'Position'             ,[c_ofs r_ofs c_wth r_wth] ...
                ,'Callback'             ,@obj.close_smc100a ...
                ,'Enable'               ,'off' ...
                );
            
            %%% Block sequence panel %%%
            
            c_ofs = 0.5025;
            r_ofs = 0.72;
            c_wth = 0.495;
            r_wth = 0.13;
            
            obj.amg.hsp7 = uipanel(...
                'Parent'              ,obj.amg.h ...
                ,'Title'              ,'R&S Parameters' ...
                ,'TitlePosition'      ,'lefttop' ...
                ,'BackgroundColor'    ,Acquisition.Default_parameters.Panel_BackgroundColor ...
                ,'ForegroundColor'    ,Acquisition.Default_parameters.Panel_ForegroundColor ...
                ,'HighlightColor'     ,Acquisition.Default_parameters.Panel_HighlightColor ...
                ,'ShadowColor'        ,Acquisition.Default_parameters.Panel_ShadowColor ...
                ,'FontName'           ,Acquisition.Default_parameters.Panel_FontName ...
                ,'FontSize'           ,Acquisition.Default_parameters.Panel_FontSize ...
                ,'FontUnits'          ,Acquisition.Default_parameters.Panel_FontUnits ...
                ,'FontWeight'         ,Acquisition.Default_parameters.Panel_FontWeight ...
                ,'SelectionHighlight' ,Acquisition.Default_parameters.Panel_SelectionHighlight ...
                ,'Units'              ,Acquisition.Default_parameters.Panel_Units ...
                ,'Position'           ,[c_ofs r_ofs c_wth r_wth] ...
                );
        end
        
        function init_pixelfly(obj,~,~)

            obj.amg_lsb1_clb;
            
            obj.amg_edt1_2_clb;
            
            set(obj.amg.but1_2,'Enable','on');
            
            set(obj.amg.but1_1,'Enable','off');
            set(obj.amg.but3_1,'Enable','off');
            
        end
        
        function init_imagingsource(obj,~,~)
            
            obj.imagingsource.init;

            obj.amg_lsb2_clb
            
            set(obj.amg.but3_2,'Enable','on');
            
            set(obj.amg.but3_1,'Enable','off');
            set(obj.amg.but1_1,'Enable','off');
            set(obj.amg.but4_1,'Enable','on');
            set(obj.amg.but4_3,'Enable','on');
            set(obj.amg.but4_4,'Enable','on');
            set(obj.amg.but4_5,'Enable','on');
            
        end
        
        function init_Tabor(obj,~,~)
            
            % initialize Tabor
            
            obj.tabor.init;
            
            % give access to configuration button

            set(obj.amg.but5_2,'Enable','on');
            set(obj.amg.but5_1,'Enable','off');
            set(obj.amg.but6_1,'Enable','on');
             
        end
        
        function init_smc100a(obj,~,~)
            
            obj.smc100a.init;
            
            % give access to configuration button

            set(obj.amg.but7_1,'Enable','off');
            set(obj.amg.but7_2,'Enable','on');
            
        end
        
        function start_acquisition(obj,~,~)
            
            switch obj.pixelfly_running
                
                case 0
                    
                    % initialize and start camera
                    
                    obj.pixelfly.StartAcquisition(); % Call the methods to prepare the camera for the acquisition
                    
                    set(obj.amg.but1_2,'BackgroundColor',[1.0,0.0,0.0]);
                    set(obj.amg.but1_2,'String','stop Acquis.');
                    
                    set(obj.amg.but1_3,'Enable','off');
                    
                    obj.pixelfly_running = 1;
                    
                    obj.pixelfly.isRunning = 1;
                    
                case 1
                    
                    % stop camera
                    
                    obj.pixelfly.StopAcquisition();  % Close the camera and clear the memory
                    
                    set(obj.amg.but1_2,'BackgroundColor',[0.0,1.0,0.0]);
                    set(obj.amg.but1_2,'String','start Acquis.');
                    
                    set(obj.amg.but1_3,'Enable','on');
                    
                    obj.pixelfly_running = 0;
                    
                    obj.pixelfly.isRunning = 0;
                    
            end
            
        end
        
        function start_acquisition2(obj,~,~)
            
            switch obj.imagingsource_running
                
                case 0
                    
                    % initialize and start camera
                    
                    obj.imagingsource.StartAcquisition(); % Call the methods to prepare the camera for the acquisition
                    
                    set(obj.amg.but3_2,'BackgroundColor',[1.0,0.0,0.0]);
                    set(obj.amg.but3_2,'String','stop Acquis.');
                    
                    set(obj.amg.but3_3,'Enable','off');
                    
                    obj.imagingsource_running = 1;
                    
                    obj.imagingsource.isRunning = 1;
                    
                case 1
                    
                    % stop camera
                    
                    obj.imagingsource.StopAcquisition();  % Close the camera and clear the memory
                    
                    set(obj.amg.but3_2,'BackgroundColor',[0.0,1.0,0.0]);
                    set(obj.amg.but3_2,'String','start Acquis.');
                    
                    set(obj.amg.but3_3,'Enable','on');
                    
                    obj.imagingsource_running = 0;
                    
                    obj.imagingsource.isRunning = 0;
                    
            end
            
        end
        
        function close_camera(obj,~,~)
            
            %delete(obj.pixelfly.imgTimer);
            
            %obj.pixelfly = [];
            
            set(obj.amg.but1_1,'Enable','on');
            set(obj.amg.but1_2,'Enable','off');
            set(obj.amg.but1_3,'Enable','off');
            set(obj.amg.but3_1,'Enable','on');
            
        end
        
        function close_camera2(obj,~,~)
            
            %delete(obj.pixelfly.imgTimer);
            stop(obj.imagingsource.vid);
            flushdata(obj.imagingsource.vid);
                     
            %obj.imagingsource = [];
            
            %imaqreset
            
            
            set(obj.amg.but3_1,'Enable','on');
            set(obj.amg.but3_2,'Enable','off');
            set(obj.amg.but3_3,'Enable','off');
            set(obj.amg.but1_1,'Enable','on');
            set(obj.amg.but4_1,'Enable','off');
            set(obj.amg.but4_3,'Enable','off');
            set(obj.amg.but4_4,'Enable','off');
            set(obj.amg.but4_5,'Enable','off');
            
        end
        
        function close_Tabor(obj,~,~)
            
            obj.tabor.close;

            set(obj.amg.but5_1,'Enable','on');
            set(obj.amg.but5_2,'Enable','off');
            set(obj.amg.but6_1,'Enable','off');
            
        end
        
        function close_smc100a(obj,~,~)
            
            obj.smc100a.close;
            
            % give access to configuration button

            set(obj.amg.but7_1,'Enable','on');
            set(obj.amg.but7_2,'Enable','off');
            
        end
        
        function amg_lsb1_clb(obj,~,~)
            
            list_cell = get(obj.amg.lsb1_1,'String');
            
            ind = get(obj.amg.lsb1_1,'Value');
            
            obj.pixelfly.imagingType = list_cell{ind};
            
        end
        
        function amg_lsb2_clb(obj,~,~)
            
            list_cell = get(obj.amg.lsb4_1,'String');
            
            ind = get(obj.amg.lsb4_1,'Value');
            
            obj.imagingsource.imagingType = list_cell{ind};
                                 
        end
        
        function amg_edt1_2_clb(obj,~,~)
            
            newExposureTime = get(obj.amg.edt1_2,'String');
            
            obj.pixelfly.exposureTime = str2double(newExposureTime);
            
        end
        
        function amg_popup1_3_clb(obj,~,~)
            
        end
        
        function amg_edt1_4_clb(obj,~,~)
            
        end
        
        
        function amg_edt6_1_clb(obj,~,~)
            
            obj.tabor.sample_rate = get(obj.amg.edt6_1,'String');
            
            invoke(obj.tabor.CnfFuncArbOut, 'configuresamplerate',str2double(obj.tabor.sample_rate)*1e6);
            
        end
        
        function execute(obj,name,message)
            
            switch name
                
                case 'BEC008'
                    
                    message = strcat(message,'');
                    
                    str_cell = strsplit(message,'-');
                    
                    switch str_cell{1}
                        
                        case 'stop'
                            
                            if obj.pixelfly.isRunning
                                
                                stop(obj.pixelfly.imagesTimer)
                                
                            end
                            
                            if obj.imagingsource.isRunning
                                
                                flushdata(obj.imagingsource.vid)
                                obj.imagingsource.framecount = 0;
                                disp('**********Pictures acquisition ended*************')
                                
                            end
                            
                        case 'seq_duration'
                            
                            obj.pixelfly.seq_duration = str2double(str_cell{2});
                            
                            obj.imagingsource.seq_duration = str2double(str_cell{2});
                            
                        case 'Tabor_sequence'
                            
                            if ~isempty(obj.tabor.dev)
                                
                                obj.tabor.load_sequence;
                                
                            end
                            
                        case 'SMC100A_sequence'
                            
                            obj.smc100a.start_freq = str2double(str_cell{3});
                            obj.smc100a.stop_freq = str2double(str_cell{5});
                            obj.smc100a.sweep_duration = str2double(str_cell{7});
                            obj.smc100a.sweep_points = str2double(str_cell{9});
                            obj.smc100a.level = str2double(str_cell{11});
                            
                            if ~isempty(obj.smc100a.dev)
                                
                                obj.smc100a.set_parameters
                                
                            end
                            
                        case 'seq'
                            
                            if obj.pixelfly.isRunning
                                
                                obj.pixelfly.current_message = strcat('pixelfly-',obj.pixelfly.imagingType,'-',message);
                                
                                start(obj.pixelfly.imagesTimer)
                                
                            end
                            
                            if obj.imagingsource.isRunning
                                
                                if obj.imagingsource.vid.FramesAvailable > 0 && obj.imagingsource.vid.FramesAvailable < obj.imagingsource.vid.FramesPerTrigger*4
                                    switch obj.imagingsource.imagingType
                                        case 'fluo_tof'
                                            
                                            disp('Image Count Fault!');
                                            
                                            
                                            obj.imagingsource.A = ones(obj.imagingsource.vid.VideoResolution*[0;1],obj.imagingsource.vid.VideoResolution*[1;0],4);
                                            
                                            pic_at     = obj.imagingsource.A(:,:,1);
                                            pic_at_bg  = obj.imagingsource.A(:,:,3);
                                            
                                            pic_wat    = obj.imagingsource.A(:,:,2);
                                            pic_wat_bg = obj.imagingsource.A(:,:,4);
                                            
                                            
                                            save(['\\E010-BEC-PC03\Data\Tmp\ImagSource\','pic_at.mat'],'pic_at');
                                            save(['\\E010-BEC-PC03\Data\Tmp\ImagSource\','pic_at_bg.mat'],'pic_at_bg');
                                            
                                            save(['\\E010-BEC-PC03\Data\Tmp\ImagSource\','pic_wat.mat'],'pic_wat');
                                            save(['\\E010-BEC-PC03\Data\Tmp\ImagSource\','pic_wat_bg.mat'],'pic_wat_bg');
                                            
                                            
                                            disp('Blanks read and saved');
                                            obj.imagingsource.framecount = 0;
                                            flushdata(obj.imagingsource.vid)
                                            
                                            obj.net.send_message('main',obj.imagingsource.current_message);
                                            
                                            disp('message sent')
                                            
                                        case 'fluo_1pix'
                                            disp('Image Count Fault!');
                                            
                                            
                                            obj.imagingsource.A = ones(obj.imagingsource.vid.VideoResolution*[0;1],obj.imagingsource.vid.VideoResolution*[1;0],2);
                                            
                                            pic_at    = obj.imagingsource.A(:,:,1);
                                            pic_at_bg = obj.imagingsource.A(:,:,2);
                                            
                                            save(['\\E010-BEC-PC03\Data\Tmp\ImagSource\','pic_at.mat'],'pic_at');
                                            save(['\\E010-BEC-PC03\Data\Tmp\ImagSource\','pic_at_bg.mat'],'pic_at_bg');
                                            
                                            disp('Blanks read and saved');
                                            obj.imagingsource.framecount = 0;
                                            flushdata(obj.imagingsource.imagingsource.vid)
                                            
                                            obj.net.send_message('main',obj.imagingsource.current_message);
                                            
                                            disp('message sent')
                                            
                                            
                                        case 'clean_abs'
                                            disp('Image Count Fault!');
                                            
                                            
                                            obj.imagingsource.A = ones(obj.imagingsource.vid.VideoResolution*[0;1],obj.imagingsource.vid.VideoResolution*[1;0],4);
                                            
                                            pic_at     = obj.imagingsource.A(:,:,1);
                                            pic_at_bg  = obj.imagingsource.A(:,:,3);
                                            
                                            pic_wat    = obj.imagingsource.A(:,:,2);
                                            pic_wat_bg = obj.imagingsource.A(:,:,4);
                                            
                                            save(['\\E010-BEC-PC03\Data\Tmp\ImagSource\','pic_at.mat'],'pic_at');
                                            save(['\\E010-BEC-PC03\Data\Tmp\ImagSource\','pic_at_bg.mat'],'pic_at_bg');
                                            
                                            save(['\\E010-BEC-PC03\Data\Tmp\ImagSource\','pic_wat.mat'],'pic_wat');
                                            save(['\\E010-BEC-PC03\Data\Tmp\ImagSource\','pic_wat_bg.mat'],'pic_wat_bg');
                                            
                                            
                                            disp('Blanks read and saved');
                                            obj.imagingsource.framecount = 0;
                                            flushdata(obj.imagingsource.vid)
                                            
                                            obj.net.send_message('main',obj.imagingsource.current_message);
                                            
                                            disp('message sent')
                                    end
                                else
                                end
                                
                                obj.imagingsource.current_message = strcat('imagsource-',obj.imagingsource.imagingType,'-',message);
                                
                                obj.imagingsource.StartAcquisition()
                                
                                disp('message updated')
                                
                            end
                            
                        otherwise
                            
                            disp('Unknown message !!!')
                            
                    end
                    
            end
            
        end
        
        
        function delete(obj)
            
            delete(obj.net);
            
        end
        
    end
    
end